In [9]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

**Importing Dataset**
1. Dataset berasal dari kaggle brazilian-ecommerce
2. Terdapat 9 dataset yang memiliki relasi satu sama lain
3. Join melalui PK atau merge dapat dilakukan untuk menyatukan data

In [23]:
customers   =  pd.read_csv ("data/olist_customers_dataset.csv")
geolocation =  pd.read_csv("data/olist_geolocation_dataset.csv")
order_items =  pd.read_csv ("data/olist_order_items_dataset.csv")
payment     =  pd.read_csv ("data/olist_order_payments_dataset.csv")
reviews     =  pd.read_csv ("data/olist_order_reviews_dataset.csv")
orders      =  pd.read_csv ("data/olist_orders_dataset.csv")
product     =  pd.read_csv ("data/olist_products_dataset.csv")
sellers     =  pd.read_csv ("data/olist_sellers_dataset.csv")
category    =  pd.read_csv ("data/product_category_name_translation.csv")

**Check kolom-kolom yang dimiliki oleh dataset**
1. Menggunakan library pandas untuk membaca file csv dan fungsi head atau tails untuk melihat beberapa kolom saja
2. Setelah dilakukan pemeriksaan head atau tail dirangkum dalam [ERD](https://drive.google.com/file/d/1Z-Qa0tShQ4gBZmhQcf2bvPf2t-Twfmgu/view?usp=sharing)

In [11]:
reviews.tail(1)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

**Menggabungkan Kolom dengan Fungsi Join atau Merge**
* fungsi join di python memiliki kemiripan dengan SQL
* terdapat 3 fungsi join utama yaitu INNER JOIN, LEFT JOIN, dan RIGHT JOIN
* atau memakai fungsi MERGE
* Melakukan Eksplorasi Statistics

In [12]:
#JOIN DATASET PERTAMA
tantut_merge_a=customers.merge(orders, on='customer_id', how='left')
tantut_merge_a.head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00

In [13]:
#JOIN DATASET KEDUA
tantut_merge_b=tantut_merge_a.merge(payment, on='order_id', how='left')
tantut_merge_b.head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00,1.0,credit_card,2.0,146.87
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00,1.0,credit_card,8.0,335.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00,1.0,credit_card,7.0,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00,1.0,credit_card,1.0,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00,1.0,credit_card,8.0,252.25

Statistical Approach Exploratory
1. Describe Dataset based On Basic Statistics
2. Check Missing Value

In [14]:
#Descriptive Statistics data Dataset merge_b
tantut_merge_b.describe()

,customer_zip_code_prefix,payment_sequential,payment_installments,payment_value
count,103887.000000,103886.000000,103886.000000,103886.000000
mean,35072.353490,1.092679,2.853349,154.100380
std,29743.416343,0.706584,2.687051,217.494064
min,1003.000000,1.000000,0.000000,0.000000
25%,11367.500000,1.000000,1.000000,56.790000
50%,24360.000000,1.000000,1.000000,100.000000
75%,58418.000000,1.000000,4.000000,171.837500
max,99990.000000,29.000000,24.000000,13664.080000

In [15]:
#Check Missing Value
a=tantut_merge_b.isna().sum()
a

customer_id                         0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_id                            0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 175
order_delivered_carrier_date     1888
order_delivered_customer_date    3132
order_estimated_delivery_date       0
payment_sequential                  1
payment_type                        1
payment_installments                1
payment_value                       1
dtype: int64

**Melakukan Eksplorasi Data Business Approach**
1. menghitung jumlah order; 
2. menghitung jumlah customer;
3. menghitung jumlah customer yang melakukan order;
4. menghitung jumlah order per order status;
5. menghitung jumlah customer per city

In [16]:
#Menghitung Jumlah order
jumlah_order=tantut_merge_b.order_id.nunique()
print('Jumlah Order:',jumlah_order)

Jumlah Order: 99441

In [17]:
#Menghitung Jumlah Customer
jumlah_customer=tantut_merge_b.customer_unique_id.nunique()
jumlah_customer

96096

In [18]:
#menghitung jumlah customer yang melakukan order
jumlah_customer_order=tantut_merge_b.customer_id.nunique()
jumlah_customer_order

99441

In [19]:
#menghitung jumlah order per order status
order_per_status=tantut_merge_b.groupby('order_status')['order_id'].nunique().reset_index()
order_per_status

  order_status  order_id
0     approved         2
1     canceled       625
2      created         5
3    delivered     96478
4     invoiced       314
5   processing       301
6      shipped      1107
7  unavailable       609

In [20]:
order_per_status.rename(columns={"order_id": "total_order"}, inplace=True)
order_per_status

  order_status  total_order
0     approved            2
1     canceled          625
2      created            5
3    delivered        96478
4     invoiced          314
5   processing          301
6      shipped         1107
7  unavailable          609

In [21]:
order_per_status.sort_values(by="total_order", ascending=False)

  order_status  total_order
3    delivered        96478
6      shipped         1107
1     canceled          625
7  unavailable          609
4     invoiced          314
5   processing          301
2      created            5
0     approved            2

In [25]:
#menghitung jumlah customer per city
customer_per_city=tantut_merge_b.groupby(['customer_city','customer_state'])['customer_unique_id','order_id'].nunique().reset_index()
customer_per_city.rename(columns={"customer_unique_id": "total_customer"}, inplace=True)
customer_per_city.rename(columns={"order_id": "order_total"}, inplace=True)
customer_per_city.sort_values(by="total_customer", ascending=False,inplace=True)

/tmp/ipykernel_6158/3376960647.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  customer_per_city=tantut_merge_b.groupby(['customer_city','customer_state'])['customer_unique_id','order_id'].nunique().reset_index()

            customer_city customer_state  total_customer  order_total
3758            sao paulo             SP           14984        15540
3281       rio de janeiro             RJ            6620         6882
469        belo horizonte             MG            2672         2773
587              brasilia             DF            2069         2131
1187             curitiba             PR            1465         1521
...                   ...            ...             ...          ...
2278        manoel urbano             AC               1            1
1365               fatima             TO               1            1
1369         faxinalzinho             RS               1            1
3397  santa clara d'oeste             SP               1            1
3445          santa maria             RN               1            1

[4310 rows x 4 columns]

In [ ]:
customer_city=tantut_merge_b.groupby(['customer_city','payment_type']).agg(
    total_customer=('customer_unique_id','nunique'),
    total_order   =('order_id','nunique'),
    total_payment =('payment_value','sum'),
)
customer_city.sort_values(by="total_payment", ascending=False)

,,total_customer,total_order,total_payment
customer_city,payment_type,,,
sao paulo,credit_card,11766,12190,1757931.79
rio de janeiro,credit_card,5332,5512,942028.03
sao paulo,boleto,2722,2783,358042.07
belo horizonte,credit_card,2153,2227,343387.39
brasilia,credit_card,1643,1688,291241.56
...,...,...,...,...
sao miguel do anta,credit_card,1,1,1.65
santo anastacio,voucher,1,1,1.29
antonio pereira,voucher,1,1,0.92
sao sebastiao de campos,credit_card,1,1,0.19
sao paulo,not_defined,3,3,0.00

Data Transformation
1. Mengubah Tanggal Menjadi tipe dari DD/MM/YYYY HH:MM:SS --> DD/MM/YYYY
2. Membuat CASE WHEN bersyarat

In [ ]:
#Mengubah Tanggal Menjadi tipe dari DD/MM/YYYY HH:MM:SS --> DD/MM/YYYY
tantut_merge_b['order_purchase_timestamp'] = pd.to_datetime(tantut_merge_b['order_purchase_timestamp']).dt.date
tantut_merge_b['order_approved_at'] = pd.to_datetime(tantut_merge_b['order_approved_at']).dt.date
tantut_merge_b['order_approved_at'] = pd.to_datetime(tantut_merge_b['order_approved_at']).dt.date
tantut_merge_b['order_delivered_carrier_date'] = pd.to_datetime(tantut_merge_b['order_delivered_carrier_date']).dt.date
tantut_merge_b['order_delivered_customer_date'] = pd.to_datetime(tantut_merge_b['order_delivered_customer_date']).dt.date
tantut_merge_b['order_estimated_delivery_date'] = pd.to_datetime(tantut_merge_b['order_estimated_delivery_date']).dt.date
tantut_merge_b

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16,2017-05-16,2017-05-23,2017-05-25,2017-06-05,1.0,credit_card,2.0,146.87
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12,2018-01-12,2018-01-15,2018-01-29,2018-02-06,1.0,credit_card,8.0,335.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19,2018-05-20,2018-06-11,2018-06-14,2018-06-13,1.0,credit_card,7.0,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13,2018-03-13,2018-03-27,2018-03-28,2018-04-10,1.0,credit_card,1.0,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29,2018-07-29,2018-07-30,2018-08-09,2018-08-15,1.0,credit_card,8.0,252.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103882,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07,2018-04-07,2018-04-11,2018-04-13,2018-04-25,1.0,credit_card,6.0,88.78
103883,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04,2018-04-04,2018-04-05,2018-04-11,2018-04-20,1.0,credit_card,3.0,129.06
103884,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08,2018-04-08,2018-04-09,2018-05-09,2018-05-02,1.0,credit_card,5.0,56.04
103885,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03,2017-11-03,2017-11-06,2017-11-16,2017-12-05,1.0,credit_card,2.0,711.07
103886,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19,2017-12-19,2017-12-21,2017-12-26,2018-01-08,1.0,credit_card,1.0,21.77

In [ ]:
#Case When in Python
tantut_merge_b.loc[(tantut_merge_b['order_status'] == 'delivered'), 'bonus_status'] = 'OK'
tantut_merge_b.loc[(tantut_merge_b['order_status'] == 'unavailable'), 'bonus_status'] = 'NEED TO FU'
tantut_merge_b.loc[(tantut_merge_b['order_status'] == 'canceled'), 'bonus_status'] = 'NEED TO RESEND'
tantut_merge_b.loc[(tantut_merge_b['order_status'] == 'shipped'), 'bonus_status'] = 'Almost OK'
tantut_merge_b.loc[(tantut_merge_b['order_status'] != 'delivered'), 'bonus_status'] = 'NOT OK'
tantut_merge_b

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value,bonus_status
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16,2017-05-16,2017-05-23,2017-05-25,2017-06-05,1.0,credit_card,2.0,146.87,OK
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12,2018-01-12,2018-01-15,2018-01-29,2018-02-06,1.0,credit_card,8.0,335.48,OK
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19,2018-05-20,2018-06-11,2018-06-14,2018-06-13,1.0,credit_card,7.0,157.73,OK
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13,2018-03-13,2018-03-27,2018-03-28,2018-04-10,1.0,credit_card,1.0,173.30,OK
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29,2018-07-29,2018-07-30,2018-08-09,2018-08-15,1.0,credit_card,8.0,252.25,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103882,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07,2018-04-07,2018-04-11,2018-04-13,2018-04-25,1.0,credit_card,6.0,88.78,OK
103883,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04,2018-04-04,2018-04-05,2018-04-11,2018-04-20,1.0,credit_card,3.0,129.06,OK
103884,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08,2018-04-08,2018-04-09,2018-05-09,2018-05-02,1.0,credit_card,5.0,56.04,OK
103885,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03,2017-11-03,2017-11-06,2017-11-16,2017-12-05,1.0,credit_card,2.0,711.07,OK
103886,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19,2017-12-19,2017-12-21,2017-12-26,2018-01-08,1.0,credit_card,1.0,21.77,OK

In [ ]:
trial=tantut_merge_b.groupby(['order_status'])['order_id'].nunique().reset_index()
trial

  order_status  order_id
0     approved         2
1     canceled       625
2      created         5
3    delivered     96478
4     invoiced       314
5   processing       301
6      shipped      1107
7  unavailable       609